on:
  push:
    branches:
      - master
  pull_request:

name: CI
jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set APP_NAME variable
        run: echo "APP_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      - name: Set DOCKERHUB_REGISTRY variable
        run: echo "DOCKERHUB_REGISTRY=osamaesmail" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and tag main image
        env:
          DOCKERHUB_REGISTRY: ${{ env.DOCKERHUB_REGISTRY }}
          DOCKERHUB_REPOSITORY: ${{ env.APP_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: docker build -t $DOCKERHUB_REGISTRY/$DOCKERHUB_REPOSITORY:$IMAGE_TAG -t $DOCKERHUB_REGISTRY/$DOCKERHUB_REPOSITORY:latest-${GITHUB_REF##*/} .
      - name: Push main image to dockerhub
        if: github.event_name != 'pull_request'
        env:
          DOCKERHUB_REGISTRY: ${{ env.DOCKERHUB_REGISTRY }}
          DOCKERHUB_REPOSITORY: ${{ env.APP_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: docker push $DOCKERHUB_REGISTRY/$DOCKERHUB_REPOSITORY --all-tags
  HelmUpdate:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: [Docker]
    steps:
      - name: Set BRANCH_NAME variable
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/} | tr / -)" >> $GITHUB_ENV
      - name: Set HELM_PATH variable
        run: echo "HELM_PATH=api" >> $GITHUB_ENV
      - name: Set HELM_REPO variable
        run: echo "HELM_REPO=osamaesmail/k8s-helm" >> $GITHUB_ENV
      - name: Check out helm chart repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.HELM_REPO }}
          path: helm-charts
          token: ${{ secrets.GIT_TOKEN }}
      - name: Update Helm values-production
        if: env.BRANCH_NAME == 'master'
        working-directory: helm-charts
        env:
          IMAGE_TAG: ${{ github.sha }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
        run: sed -E -i'' "s/(.*tag:).*/\1 ${IMAGE_TAG}/" ${HELM_PATH}/values.yaml
      - name: Setup Git for push
        working-directory: helm-charts
        env:
          GIT_USERNAME: "${{ secrets.GIT_USERNAME }}"
          GIT_EMAIL: ${{ secrets.GIT_USERNAME }}@gmail.com
        run: git config --local user.name $GIT_USERNAME && git config --local user.email $GIT_EMAIL
      - name: Commit helm changes
        working-directory: helm-charts
        env:
          HELM_PATH: ${{ env.HELM_PATH }}
          IMAGE_TAG: ${{ github.sha }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
        run: git add ./${HELM_PATH} && git diff-index --quiet HEAD || (git commit -m "updated ${HELM_PATH} on ${BRANCH_NAME} with image tag ${IMAGE_TAG}" && git push)
